[is_fallen]
MIN_OK_PARTS = 3
LS_Y = 0.55
RS_Y = 0.55
LK_Y = 0.65
RK_Y = 0.65
FALL_COUNT = 3

[is_fallen_model]
FALL_PROBABILITY = 0.5

[is_fallen_Upperbody]
MIN_OK_PARTS = 1
LS_Y = 0.90
RS_Y = 0.90
FALL_COUNT = 2